# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 08:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('status', models.CharField(blank=True, choices=[('in_stock', 'Доступний на складі'), ('hired', 'У прокаті'), ('needs_repairs', 'Потребує ремонту'), ('under_repair', 'У ремонті')], max_length=24, null=True, verbose_name='Статус')),
                ('title', models.CharField(blank=True, max_length=64, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Обладнання',
                'verbose_name_plural': 'Обладнання',
            },
        ),
        migrations.CreateModel(
            name='EquipmentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_status', models.CharField(max_length=24, verbose_name='Статус до')),
                ('post_status', models.CharField(max_length=24, verbose_name='Статус після')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('iteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Equipment', verbose_name='Обладнання')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Дія з обладнанням',
                'verbose_name_plural': 'Дії з обладнанням',
            },
        ),
    ]
